version: "2"
services:
  penpal-frontend:
    volumes:
      - ./PenPal/app/src/:/penpal/app/src
      - ./PenPal/app/static/:/penpal/app/static
      - ./PenPal/app/package-frontend.json:/penpal/app/package-tmp.json
      - ./PenPal/app/vite.config.js:/penpal/app/vite.config.js
      - ./plugins/:/penpal/app/plugins
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}

  penpal-server:
    volumes:
      - ./PenPal/app/src/:/penpal/app/src
      - ./PenPal/app/nodemon.config.json:/penpal/app/nodemon.config.json
      - ./PenPal/app/package-server.json:/penpal/app/package-tmp.json
      - ./plugins/:/penpal/app/plugins:consistent
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - FORCE_COLOR=1
