services:
  penpal-frontend:
    volumes:
      # Mount package.json read-only to prevent bun changes from propagating
      - ./PenPal/app/client/package.json:/penpal/package-tmp.json:ro
      - ./PenPal/app/client/vite.config.js:/penpal/vite.config.js:ro
      - ./PenPal/app/client/src:/penpal/src
      - ./Plugins:/penpal/plugins
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - CONTAINER_TYPE=frontend

  penpal-server:
    volumes:
      # Mount package.json read-only to prevent bun changes from propagating
      - ./PenPal/app/server/package.json:/penpal/package-tmp.json:ro
      - ./PenPal/app/server/nodemon.config.json:/penpal/nodemon.config.json:ro
      - ./PenPal/app/server/src:/penpal/src
      - ./Plugins:/penpal/plugins
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - FORCE_COLOR=1
      - CONTAINER_TYPE=server
